spring.application.name=${SPRING_APPLICATION_NAME}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${SERVER_PORT}

app.jwt.secret=${JWT_SECRET}
app.jwt.access-expiration=${JWT_ACCESS_EXPIRATION}
app.jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}

app.token.verification-expiration=${TOKEN_VERIFICATION_EXPIRATION}
app.token.password-reset-expiration=${TOKEN_PASSWORD_RESET_EXPIRATION}

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.oauth2.client.registration.google.client-id=${GG_OAUTH2_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GG_OAUTH2_CLIENT_SECRET}
app.oauth2.redirect-uri=${OAUTH2_REDIRECT_URI:http://localhost:3000/oauth2/redirect}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}